[package]
name = "zip-abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="zip"
crate-type=["cdylib"]

[dependencies]
zip = "0.6.6"
walkdir = "2"
